Sb atomicdocs domain
atomicjolt/adhesion pull request #463
Opened 2021-03-24 21:56 UTC by spencerAJ

Pivotal Tracker:
- [#176963073](https://www.pivotaltracker.com/story/show/176963073) - Integrate global javascript with adhesion
- [#177063936](https://www.pivotaltracker.com/story/show/177063936) - Move docviewer to atomicdocs subdomain

These changes move all code for the docviewer app to the atomicdocs subdomain. Only ".pdf" file types are supported. Existing atomicdocs code was left in place in order to easily allocate development time back to the project when we have approval from AU to move forward with the libreoffice conversion.

2021-03-25 17:17 UTC, srphillips reviewed
I understand that jQuery and Lodash are being used in the global js script but hound sees them as undefined.  Are we assured that both will be available wherever this gets imported for use because of the webpack stuff?  Let me know

I also think we may get some comments on how we're doing the webpack stuff once we get this in front of other eyes for merge into main adhesion, so there may be changes to be made later.

2021-03-25 17:17 UTC, srphillips commented on client/apps/atomic_docs/components/layout/index.spec.jsx
> +// import React from 'react';
Let's not just comment out a whole spec and then leave it in the app code.  Lets try to fix it if it doesn't work.  If you think it doesn't perform a useful test anymore, then we can talk about what to do instead.

2021-03-26 15:48 UTC, srphillips requested changes
A few things that still need to be removed.  Please see my notes about jQuery.  I'm always hesitant to bring something that big into a project that doesn't already have it.

2021-03-26 15:48 UTC, srphillips commented on client/apps/atomic_docs/components/layout/index.spec.jsx
> +  console.log("children", children);
Dont think this console log was supposed to be left in

2021-03-26 15:48 UTC, srphillips commented on client/packs/global_javascript.js
> +          iframeHolder.append(`<iframe id="atomicdocs" allow="fullscreen" src="https://${CANVAS_DOMAIN}/courses/${ENV.course_id}/external_tools/retrieve?display=borderless&url=https://atomicdocs.atom
I think so

2021-03-26 15:48 UTC, srphillips commented on client/packs/global_javascript.js
> +const $ = require('jquery');
If there's a way to do this without jquery so that we don't have to bring it into the project, I'd prefer that.  Perhaps I'll let this merge and we can adjust before merging into master if there's argument.

2021-03-26 15:48 UTC, srphillips commented on package.json
> +    "jquery": "^3.6.0",
See Above: If there's a way to do this without jquery so that we don't have to bring it into the project, I'd prefer that. Perhaps I'll let this merge and we can adjust before merging into master if there's argument.

2021-03-26 22:44 UTC, spencerAJ commented on client/packs/global_javascript.js
> +        const previewFrame = $('#preview_frame');
JQuery seems to be available throughout canvas. We figured it would be best to ignore these lint errors rather than including the entire package in adhesion.

2021-03-29 15:22 UTC, srphillips commented on app/controllers/api/atomic_docs_controller.rb
> +      render json: { error: "invalid_file_type" }, status: 403
I'm ok ignoring this one

2021-03-29 15:22 UTC, srphillips commented on config/webpack/environment.js
> -// const CopyPlugin = require('copy-webpack-plugin')
Lets remove the commented stuff in here if it isn't working or worth keeping.

2021-03-29 15:26 UTC, srphillips commented on client/packs/global_javascript.js
> +        const previewFrame = $('#preview_frame');
This seems to be fine.  We can discuss it with others if necessary when merging into master.

2021-03-29 15:46 UTC, spencerAJ commented on config/webpack/environment.js
> -// const CopyPlugin = require('copy-webpack-plugin')
This is a deletion so commented code has already been removed

2021-03-29 15:48 UTC, srphillips commented on config/webpack/environment.js
> -// const CopyPlugin = require('copy-webpack-plugin')
Haha, I'm just blind this morning...

2021-03-29 15:50 UTC, srphillips approved these changes

2021-03-29 15:59 UTC, merged